/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import vista.interfaces.ICambioPassword;

import java.awt.Color;
/**
 *
 * @author Usuario
 */
public class JFCambioPassword extends javax.swing.JFrame implements ICambioPassword {
    int xMouse, yMouse;
    /**
     * Creates new form JFCambioPassword
     */
    public JFCambioPassword() {
        initComponents();
        jpfActual.setName(JPF_ACTUAL);
        jpfNueva.setName(JPF_NUEVO);
        jbtAceptar.setName(JBT_ACEPTAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtAceptar = new javax.swing.JButton();
        jpfActual = new javax.swing.JPasswordField();
        jpfNueva = new javax.swing.JPasswordField();
        exitPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actual Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jbtAceptar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtAceptar.setText("Aceptar");
        getContentPane().add(jbtAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 143, 330, 30));

        jpfActual.setBorder(null);
        getContentPane().add(jpfActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 30));

        jpfNueva.setBorder(null);
        getContentPane().add(jpfNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 92, 280, 30));

        exitPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitPanel.setOpaque(false);
        exitPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPanelMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("X");
        exitPanel.add(jLabel11);

        getContentPane().add(exitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 50, 50));

        jPanel1.setOpaque(false);
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitPanelMouseClicked

    private void exitPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseEntered
        exitPanel.setBackground(Color.red);
        exitPanel.setOpaque(true);
        exitPanel.setForeground(Color.black);
    }//GEN-LAST:event_exitPanelMouseEntered

    private void exitPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPanelMouseExited
        exitPanel.setBackground(Color.white);
        exitPanel.setForeground(Color.white);
        exitPanel.setOpaque(false);
    }//GEN-LAST:event_exitPanelMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exitPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtAceptar;
    private javax.swing.JPasswordField jpfActual;
    private javax.swing.JPasswordField jpfNueva;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(LoginController c) {
        jbtAceptar.addActionListener(c);
    }

    @Override
    public void arranca() {
        this.setVisible(true);
        getRootPane().setDefaultButton(jbtAceptar);
        centrarVentana();
    }
    
    @Override
    public void ocultar() {
        this.dispose();
    }
    
    public void centrarVentana() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int anchoVentana = getWidth();
        int altoVentana = getHeight();
    
        int x = (dim.width - anchoVentana) / 2;
        int y = (dim.height - altoVentana) / 2;
    
        setLocation(x, y);
    }

    @Override
    public void mostrarPanel(String txt) {
        JOptionPane.showMessageDialog(null, txt);
    }

    @Override
    public void limpiarTexto() {
        jpfActual.setText("");
        jpfNueva.setText("");
    }

    @Override
    public void enfocar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void seleccionarText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void setTitulo(String txt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getObjeto(String id) {
        Object obj = null;
        switch (id) {
            case JBT_ACEPTAR:
                obj = jbtAceptar;
                break;
            default:
                throw new AssertionError();
        }
        return obj;
    }

    @Override
    public void setTexto(String obj, String txt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String getTexto(String obj) {
        String txt = null;
        switch (obj) {
            case JPF_ACTUAL:
                txt = new String(jpfActual.getPassword());
                break;
            case JPF_NUEVO:
                txt = new String(jpfNueva.getPassword());
                break;
            default:
                throw new AssertionError();
        }
        return txt;
    }

    @Override
    public void limpiarTexto(String obj) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
