/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.interfaces.ILogin;
import controlador.LoginController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFLogin extends javax.swing.JFrame implements ILogin {

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        jbtAceptar.setName(JBT_ACEPTAR);
        jtfUsuario.setName(JTF_USUARIO);
        jpfPassword.setName(JPF_PASSWORD);
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfUsuario = new javax.swing.JTextField();
        jbtAceptar = new javax.swing.JButton();
        jbtLimpiar = new javax.swing.JButton();
        jpfPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - SAMC");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfUsuario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jtfUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfUsuario.setText("Ingresar correo electronico");
        jtfUsuario.setBorder(null);
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 251, 30));

        jbtAceptar.setBackground(new java.awt.Color(102, 204, 255));
        jbtAceptar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jbtAceptar.setText("Ingresar");
        jbtAceptar.setBorder(null);
        getContentPane().add(jbtAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 251, 30));

        jbtLimpiar.setBackground(new java.awt.Color(255, 102, 102));
        jbtLimpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtLimpiar.setBorder(null);
        getContentPane().add(jbtLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 30, 20));

        jpfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpfPassword.setText("1234");
        jpfPassword.setBorder(null);
        jpfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 251, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WhatsApp_Image_2023-09-25_at_1.09.35_PM-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 80, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-icon-png-pnglogocom-133466 (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 250, 230));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 410, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image (1).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtAceptar;
    private javax.swing.JButton jbtLimpiar;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void setControlador(LoginController c) {
        jbtAceptar.addActionListener(c);
        jbtLimpiar.addActionListener(c);
    }

    @Override
    public ArrayList<String> getCredenciales() {
        ArrayList<String> lista = null;
        if (!jtfUsuario.getText().isEmpty() && !new String(jpfPassword.getPassword()).isEmpty()) {
            lista = new ArrayList<>();
            lista.add(jtfUsuario.getText());
            lista.add(new String(jpfPassword.getPassword()));
        } else {
            mostrarPanel(DATOS_INCOMPLETO);
        }
        return lista;
    }
    
    // <editor-fold defaultstate="collapsed" desc="IPadre">
    @Override
    public void arranca() {
        this.setVisible(true);
        getRootPane().setDefaultButton(jbtAceptar);
        centrarVentana();
    }
    
    @Override
    public void ocultar() {
        this.setVisible(false);
    }
    
    public void centrarVentana() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int anchoVentana = getWidth();
        int altoVentana = getHeight();
    
        int x = (dim.width - anchoVentana) / 2;
        int y = (dim.height - altoVentana) / 2;
    
        setLocation(x, y);
    }

    @Override
    public void mostrarPanel(String txt) {
        JOptionPane.showMessageDialog(null, txt);
    }

    @Override
    public void limpiarTexto() {
        jtfUsuario.setText("");
        jpfPassword.setText("");
    }

    @Override
    public void enfocar() {
        jtfUsuario.requestFocus();
    }

    @Override
    public void seleccionarText() {
        jtfUsuario.selectAll();
    }

    @Override
    public void setTitulo(String txt) {
        this.setTitle(txt);
    }
    
    @Override
    public Object getObjeto(String id) {
        Object o = null;
        switch (id) {
            case JBT_ACEPTAR:
                o = jbtAceptar;
                break;
            case JBT_LIMPIAR:
                o = jbtLimpiar;
                break;
            default:
                throw new AssertionError();
        }
        return o;
    }
    // </editor-fold>

    @Override
    public void setTexto(String obj, String txt) {
    }

    @Override
    public void limpiarTexto(String obj) {
        switch (obj) {
            case JTF_USUARIO:
                jtfUsuario.setText("");
                break;
            case JPF_PASSWORD:
                jpfPassword.setText("");
                break;
            default:
                throw new AssertionError();
        }
    }

}
