/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import vista.interfaces.IPerfil;
//import controlador.PerfilController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFPerfil extends javax.swing.JFrame implements IPerfil {

    /**
     * Creates new form JFPerfil
     */
    public JFPerfil() {
        initComponents();
        jlbBienvenida.setName(JLB_BIENVENIDA);
        jtfUsuario.setName(JTF_USUARIO);
        jtfNombre.setName(JTF_NOMBRE);
        jtfApellido.setName(JTF_APELLIDO);
        jtfEmail.setName(JTF_EMAIL);
        jtfFCreacion.setName(JTF_FCREACION);
        jckbActivo.setName(JCKB_ACTIVO);
        jckbAdmin.setName(JCKB_ADMIN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jckbActivo = new javax.swing.JCheckBox();
        jckbAdmin = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jtfFCreacion = new javax.swing.JTextField();
        jlbBienvenida = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 82, -1));

        jtfUsuario.setBorder(null);
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 208, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 82, -1));

        jtfNombre.setBorder(null);
        getContentPane().add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 208, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 82, -1));

        jtfApellido.setBorder(null);
        getContentPane().add(jtfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 208, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 82, -1));

        jtfEmail.setBorder(null);
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 208, 20));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton1.setText("Cambiar Contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 152, -1));

        jckbActivo.setBackground(new java.awt.Color(102, 204, 255));
        jckbActivo.setText("Activo");
        getContentPane().add(jckbActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jckbAdmin.setBackground(new java.awt.Color(102, 204, 255));
        jckbAdmin.setText("Admin");
        getContentPane().add(jckbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Fecha creación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jtfFCreacion.setBorder(null);
        getContentPane().add(jtfFCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 208, 20));

        jlbBienvenida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbBienvenida.setText("Hola NOMBRE_APELLIDO,");
        getContentPane().add(jlbBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 145, 332, -1));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuario-60.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 72, -1, 54));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WhatsApp_Image_2023-09-25_at_1.09.35_PM-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 90, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 410, 400));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jckbActivo;
    private javax.swing.JCheckBox jckbAdmin;
    private javax.swing.JLabel jlbBienvenida;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFCreacion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
    
    // <editor-fold defaultstate="collapsed" desc="IPadre">
    @Override
    public void arranca() {
        this.setVisible(true);
//        getRootPane().setDefaultButton(jbtAceptar);
        centrarVentana();
    }
    
    @Override
    public void ocultar() {
        this.setVisible(false);
    }
    
    public void centrarVentana() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int anchoVentana = getWidth();
        int altoVentana = getHeight();
    
        int x = (dim.width - anchoVentana) / 2;
        int y = (dim.height - altoVentana) / 2;
    
        setLocation(x, y);
    }

    @Override
    public void mostrarPanel(String txt) {
        JOptionPane.showMessageDialog(null, txt);
    }

    @Override
    public void limpiarTexto() {
//        jtfUsuario.setText("");
//        jpfPassword.setText("");
//        jtfUsuario.requestFocus();
    }

    @Override
    public void enfocar() {
//        jtfUsuario.requestFocus();
    }

    @Override
    public void seleccionarText() {
//        jtfUsuario.selectAll();
    }

    @Override
    public void setTitulo(String txt) {
        this.setTitle(txt);
    }
    
    @Override
    public Object getObjeto(String id) {
        Object o = null;
//        switch (id) {
//            case JMIPERFIL:
//                o = jmiPerfil;
//                break;
//            default:
//                throw new AssertionError();
//        }
        return o;
    }
    // </editor-fold>

    @Override
    public void setControlador(LoginController c) {
        
    }

    @Override
    public void setTexto(String obj, String txt) {
        switch (obj) {
            case JLB_BIENVENIDA:
                jlbBienvenida.setText(txt);
                break;
            case JTF_USUARIO:
                jtfUsuario.setText(txt);
                break;
            case JTF_NOMBRE:
                jtfNombre.setText(txt);
                break;
            case JTF_APELLIDO:
                jtfApellido.setText(txt);
                break;
            case JTF_EMAIL:
                jtfEmail.setText(txt);
                break;
            case JTF_FCREACION:
                jtfFCreacion.setText(txt);
                break;
            case JCKB_ACTIVO:
                jckbActivo.setSelected(Boolean.parseBoolean(txt));
                break;
            case JCKB_ADMIN:
                jckbAdmin.setSelected(Boolean.parseBoolean(txt));
                break;
            default:
                throw new AssertionError();
        }
    }

    @Override
    public void limpiarTexto(String obj) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
