/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import vista.interfaces.IPerfil;
//import controlador.PerfilController;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFPerfil extends javax.swing.JFrame implements IPerfil {

    private DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    /**
     * Creates new form JFPerfil
     */
    public JFPerfil() {
        initComponents();
        jlbBienvenida.setName(JLB_BIENVENIDA);
        jtfUsuario.setName(JTF_USUARIO);
        jtfNombre.setName(JTF_NOMBRE);
        jtfApellido.setName(JTF_APELLIDO);
        jtfEmail.setName(JTF_EMAIL);
        jtfFCreacion.setName(JTF_FCREACION);
        jtfFModificacion.setName(JTF_FMODIFICACION);
        jckbActivo.setName(JCKB_ACTIVO);
        jcbRol.setName(JCB_ROL);
        jbtCambiarPassword.setName(JBT_CAMBIARPASSWORD);
        jbtCerrar.setName(JBT_CERRAR);
        jbtGuardar.setName(JBT_GUARDAR);
        setSize(503, 352);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jbtCambiarPassword = new javax.swing.JButton();
        jckbActivo = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jtfFCreacion = new javax.swing.JTextField();
        jlbBienvenida = new javax.swing.JLabel();
        jbtGuardar = new javax.swing.JButton();
        jbtCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfFModificacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbRol = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 76, 90, -1));

        jtfUsuario.setEditable(false);
        jtfUsuario.setBorder(null);
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 73, 208, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 109, 90, -1));

        jtfNombre.setBorder(null);
        getContentPane().add(jtfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 106, 208, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 149, 90, -1));

        jtfApellido.setBorder(null);
        getContentPane().add(jtfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 146, 208, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 180, 90, -1));

        jtfEmail.setBorder(null);
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 177, 208, 20));

        jbtCambiarPassword.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jbtCambiarPassword.setText("Cambiar Contraseña");
        jbtCambiarPassword.setBorder(null);
        getContentPane().add(jbtCambiarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 72, -1, -1));

        jckbActivo.setText("Activo");
        getContentPane().add(jckbActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 105, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha creación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 211, 90, -1));

        jtfFCreacion.setEditable(false);
        jtfFCreacion.setBorder(null);
        getContentPane().add(jtfFCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 208, 208, 20));

        jlbBienvenida.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jlbBienvenida.setText("Hola NOMBRE_APELLIDO,");
        getContentPane().add(jlbBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 25, 475, -1));

        jbtGuardar.setBackground(new java.awt.Color(102, 204, 255));
        jbtGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jbtGuardar.setText("Guardar");
        jbtGuardar.setBorder(null);
        getContentPane().add(jbtGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 60, 20));

        jbtCerrar.setBackground(new java.awt.Color(102, 204, 255));
        jbtCerrar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jbtCerrar.setText("Cerrar");
        jbtCerrar.setBorder(null);
        getContentPane().add(jbtCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 60, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha modificación");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 242, -1, -1));

        jtfFModificacion.setEditable(false);
        jtfFModificacion.setBorder(null);
        getContentPane().add(jtfFModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 239, 208, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rol");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 273, 90, -1));

        jcbRol.setBorder(null);
        getContentPane().add(jcbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 270, 208, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, 320));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/image (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtCambiarPassword;
    private javax.swing.JButton jbtCerrar;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JComboBox<String> jcbRol;
    private javax.swing.JCheckBox jckbActivo;
    private javax.swing.JLabel jlbBienvenida;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFCreacion;
    private javax.swing.JTextField jtfFModificacion;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
    
    // <editor-fold defaultstate="collapsed" desc="IPadre">
    @Override
    public void arranca() {
        this.setVisible(true);
//        getRootPane().setDefaultButton(jbtAceptar);
        centrarVentana();
    }
    
    @Override
    public void ocultar() {
        this.setVisible(false);
    }
    
    public void centrarVentana() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int anchoVentana = getWidth();
        int altoVentana = getHeight();
    
        int x = (dim.width - anchoVentana) / 2;
        int y = (dim.height - altoVentana) / 2;
    
        setLocation(x, y);
    }

    @Override
    public void mostrarPanel(String txt) {
        JOptionPane.showMessageDialog(null, txt);
    }

    @Override
    public void limpiarTexto() {
//        jtfUsuario.setText("");
//        jpfPassword.setText("");
//        jtfUsuario.requestFocus();
    }

    @Override
    public void enfocar() {
//        jtfUsuario.requestFocus();
    }

    @Override
    public void seleccionarText() {
//        jtfUsuario.selectAll();
    }

    @Override
    public void setTitulo(String txt) {
        this.setTitle(txt);
    }
    
    @Override
    public Object getObjeto(String id) {
        Object o = null;
        switch (id) {
            case JBT_CAMBIARPASSWORD:
                o = jbtCambiarPassword;
                break;
            case JBT_CERRAR:
                o = jbtCerrar;
                break;
            case JBT_GUARDAR:
                o = jbtGuardar;
                break;
            default:
                throw new AssertionError();
        }
        return o;
    }
    // </editor-fold>

    @Override
    public void setControlador(LoginController c) {
        jbtCambiarPassword.addActionListener(c);
        jbtGuardar.addActionListener(c);
        jbtCerrar.addActionListener(c);
    }

    @Override
    public void setTexto(String obj, String txt) {
        switch (obj) {
            case JLB_BIENVENIDA:
                jlbBienvenida.setText(txt);
                break;
            case JTF_USUARIO:
                jtfUsuario.setText(txt);
                break;
            case JTF_NOMBRE:
                jtfNombre.setText(txt);
                break;
            case JTF_APELLIDO:
                jtfApellido.setText(txt);
                break;
            case JTF_EMAIL:
                jtfEmail.setText(txt);
                break;
            case JTF_FCREACION:
                jtfFCreacion.setText(txt);
                break;
            case JTF_FMODIFICACION:
                jtfFModificacion.setText(txt);
                break;
            case JCKB_ACTIVO:
                jckbActivo.setSelected(Boolean.parseBoolean(txt));
                break;
            case JCB_ROL:
                jcbRol.setSelectedIndex(Integer.parseInt(txt));
                break;
            default:
                throw new AssertionError();
        }
    }

    @Override
    public void limpiarTexto(String obj) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actualizarRoles(String[] data) {
        model = new DefaultComboBoxModel<>(data);
//        jcbRol = new JComboBox<>(model);
        jcbRol.setModel(model);
        
        jcbRol.revalidate();
    }

    @Override
    public void setHabilitar(String obj, boolean b) {
        switch (obj) {
            case JCKB_ACTIVO:
                jckbActivo.setEnabled(b);
                break;
            case JCB_ROL:
                jcbRol.setEnabled(b);
                break;
            default:
                throw new AssertionError();
        }
    }

    @Override
    public String getTexto(String obj) {
        String txt = null;
        switch (obj) {
            case JTF_NOMBRE:
                txt = jtfNombre.getText();
                break;
            case JTF_APELLIDO:
                txt = jtfApellido.getText();
                break;
            case JTF_EMAIL:
                txt = jtfEmail.getText();
                break;
            default:
                throw new AssertionError();
        }
        return txt;
    }
}
